import { Material, Profile, Project, ProjectMaterial, Supplier, Transaction, WorkLog } from '@/types';

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'prof-1',
    fullName: 'Mohsin (Jefe)',
    role: 'jefe',
    hourlyRate: 25.00,
    phone: '612 345 678',
  },
  {
    id: 'prof-2',
    fullName: 'Karim (Oficial / Empleado)',
    role: 'empleado',
    hourlyRate: 15.00,
    phone: '699 876 543',
  },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-1',
    name: 'Bricomart / Obramat',
    phone: '912 345 600',
    address: 'Polígono Industrial Las Mercedes',
  },
  {
    id: 'sup-2',
    name: 'Pladur & Aislamientos Saltoki',
    phone: '913 456 700',
    address: 'Av. de la Industria 24',
  },
  {
    id: 'sup-3',
    name: 'Almacenes Yesos del Sur',
    phone: '914 567 800',
    address: 'Ctra. de Toledo km 12',
  },
];

export const INITIAL_MATERIALS: Material[] = [
  {
    id: 'mat-1',
    supplierId: 'sup-2',
    supplierName: 'Pladur & Aislamientos Saltoki',
    name: 'Placa 13mm Blanca Estándar (2.50 x 1.20m)',
    category: 'Placas y Paneles',
    unitType: 'm2',
    coveragePerUnit: 3.00, // 2.50m x 1.20m = 3.00 m2
    unitCost: 8.50, // Coste de compra de 1 placa
    defaultWastePercentage: 5.0,
    notes: 'Placa estándar para tabiques y trasdosados interiores',
  },
  {
    id: 'mat-2',
    supplierId: 'sup-2',
    supplierName: 'Pladur & Aislamientos Saltoki',
    name: 'Placa 13mm Verde Hidrófuga (2.50 x 1.20m)',
    category: 'Placas y Paneles',
    unitType: 'm2',
    coveragePerUnit: 3.00,
    unitCost: 12.90,
    defaultWastePercentage: 5.0,
    notes: 'Especial para baños y cocinas resistentes a humedad',
  },
  {
    id: 'mat-3',
    supplierId: 'sup-1',
    supplierName: 'Bricomart / Obramat',
    name: 'Montante 48mm galvanizado (3.00 metros)',
    category: 'Perfilería',
    unitType: 'ml',
    coveragePerUnit: 3.00, // Cada perfil mide 3 metros
    unitCost: 4.80,
    defaultWastePercentage: 5.0,
    notes: 'Estructura vertical tabiquería',
  },
  {
    id: 'mat-4',
    supplierId: 'sup-1',
    supplierName: 'Bricomart / Obramat',
    name: 'Canal 48mm galvanizado (3.00 metros)',
    category: 'Perfilería',
    unitType: 'ml',
    coveragePerUnit: 3.00,
    unitCost: 3.95,
    defaultWastePercentage: 5.0,
    notes: 'Guías suelo y techo',
  },
  {
    id: 'mat-5',
    supplierId: 'sup-3',
    supplierName: 'Almacenes Yesos del Sur',
    name: 'Pasta para juntas secado rápido (Saco 25kg)',
    category: 'Pastas y Adhesivos',
    unitType: 'saco',
    coveragePerUnit: 25.00, // Aprox 25 m2 por saco
    unitCost: 18.50,
    defaultWastePercentage: 5.0,
    notes: 'Tratamiento de juntas con cinta',
  },
  {
    id: 'mat-6',
    supplierId: 'sup-3',
    supplierName: 'Almacenes Yesos del Sur',
    name: 'Rollo cinta de papel microporosa (150m)',
    category: 'Pastas y Adhesivos',
    unitType: 'rollo',
    coveragePerUnit: 150.00,
    unitCost: 7.20,
    defaultWastePercentage: 5.0,
    notes: 'Refuerzo de juntas',
  },
  {
    id: 'mat-7',
    supplierId: 'sup-1',
    supplierName: 'Bricomart / Obramat',
    name: 'Caja tornillos PM 25mm (1000 uds)',
    category: 'Tornillería',
    unitType: 'caja',
    coveragePerUnit: 50.00, // 1 caja para aprox 50 m2
    unitCost: 9.90,
    defaultWastePercentage: 5.0,
    notes: 'Fijación placa a montante de chapa',
  },
  {
    id: 'mat-8',
    supplierId: 'sup-1',
    supplierName: 'Bricomart / Obramat',
    name: 'Lana de roca acústica espesor 45mm (Paquete 7.2m2)',
    category: 'Aislamiento',
    unitType: 'm2',
    coveragePerUnit: 7.20,
    unitCost: 28.50,
    defaultWastePercentage: 5.0,
    notes: 'Aislamiento térmico y acústico interior tabique',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'Reforma Integral Calle Mayor 14',
    clientName: 'Antonio Morales',
    clientPhone: '611 222 333',
    address: 'Calle Mayor 14, 3ºB, Madrid',
    status: 'activa',
    budgetedAmount: 10000.00,
    vatRate: 21.0,
    totalCharged: 4000.00, // Adelanto cobrado
    startDate: '2026-09-01',
    notes: 'Reforma completa de tabiques, aislamiento y techos de pladur',
  },
  {
    id: 'proj-2',
    name: 'Local Comercial Cafetería Sol',
    clientName: 'Marta Gómez',
    clientPhone: '622 333 444',
    address: 'Plaza del Sol 8, Madrid',
    status: 'activa',
    budgetedAmount: 7800.00,
    vatRate: 21.0,
    totalCharged: 3500.00,
    startDate: '2026-09-05',
    notes: 'Divisiones acústicas e insonorización de techos desmontables',
  },
  {
    id: 'proj-3',
    name: 'Vivienda Unifamiliar Las Rozas',
    clientName: 'Carlos Benítez',
    clientPhone: '633 444 555',
    address: 'Calle Encinas 22, Las Rozas',
    status: 'presupuesto',
    budgetedAmount: 15400.00,
    vatRate: 10.0,
    totalCharged: 0.00,
    startDate: '2026-09-20',
    notes: 'Presupuesto pendiente de firma para trasdosados hidrófugos y techos',
  },
  {
    id: 'proj-4',
    name: 'Oficina Paseo de la Castellana',
    clientName: 'Inversiones Centro S.L.',
    clientPhone: '915 999 888',
    address: 'Pº Castellana 120, 5ª Planta',
    status: 'finalizada',
    budgetedAmount: 6500.00,
    vatRate: 21.0,
    totalCharged: 6500.00,
    startDate: '2026-08-01',
    completedAt: '2026-08-28T18:00:00Z',
    notes: 'Obra concluida con éxito y liquidada al 100%',
  },
];

export const INITIAL_PROJECT_MATERIALS: ProjectMaterial[] = [
  // Obra Calle Mayor:
  {
    id: 'pm-1',
    projectId: 'proj-1',
    materialId: 'mat-1',
    materialName: 'Placa 13mm Blanca Estándar (2.50 x 1.20m)',
    unitType: 'm2',
    requiredQuantity: 38.00,
    wastePercentage: 5.0,
    quantityWithWaste: 39.90, // 38 * 1.05
    coveragePerUnit: 3.00,
    calculatedUnits: 14, // Math.ceil(39.9 / 3.0)
    unitCost: 8.50,
    totalCost: 119.00, // 14 * 8.50
    isPurchased: true,
    purchaseDate: '2026-09-02',
  },
  {
    id: 'pm-2',
    projectId: 'proj-1',
    materialId: 'mat-3',
    materialName: 'Montante 48mm galvanizado (3.00 metros)',
    unitType: 'ml',
    requiredQuantity: 60.00,
    wastePercentage: 5.0,
    quantityWithWaste: 63.00,
    coveragePerUnit: 3.00,
    calculatedUnits: 21,
    unitCost: 4.80,
    totalCost: 100.80,
    isPurchased: true,
    purchaseDate: '2026-09-02',
  },
  {
    id: 'pm-3',
    projectId: 'proj-1',
    materialId: 'mat-5',
    materialName: 'Pasta para juntas secado rápido (Saco 25kg)',
    unitType: 'saco',
    requiredQuantity: 40.00,
    wastePercentage: 5.0,
    quantityWithWaste: 42.00,
    coveragePerUnit: 25.00,
    calculatedUnits: 2,
    unitCost: 18.50,
    totalCost: 37.00,
    isPurchased: false,
  },
];

export const INITIAL_WORK_LOGS: WorkLog[] = [
  // Parte 1: 8 horas a 15€/h (120€)
  {
    id: 'wl-1',
    projectId: 'proj-1',
    projectName: 'Reforma Integral Calle Mayor 14',
    workerId: 'prof-2',
    workerName: 'Karim (Oficial / Empleado)',
    workDate: '2026-09-08',
    workType: 'horas',
    hoursWorked: 8,
    hourlyRate: 15.00,
    totalPayout: 120.00,
    notes: 'Montaje de estructura perfilería metálica y replanteo de tabiques',
  },
  // Parte 2: 20 metros de tabique reforzado a 8€/m (160€)
  {
    id: 'wl-2',
    projectId: 'proj-1',
    projectName: 'Reforma Integral Calle Mayor 14',
    workerId: 'prof-2',
    workerName: 'Karim (Oficial / Empleado)',
    workDate: '2026-09-09',
    workType: 'metros',
    concept: 'Tabique reforzado con lana de roca',
    quantityMeters: 20.00,
    ratePerMeter: 8.00,
    totalPayout: 160.00,
    notes: 'Colocación de placas 13mm en ambas caras y aislamiento',
  },
  // Parte 3: Horas del jefe supervisando y trabajando
  {
    id: 'wl-3',
    projectId: 'proj-1',
    projectName: 'Reforma Integral Calle Mayor 14',
    workerId: 'prof-1',
    workerName: 'Mohsin (Jefe)',
    workDate: '2026-09-08',
    workType: 'horas',
    hoursWorked: 5,
    hourlyRate: 25.00,
    totalPayout: 125.00,
    notes: 'Replanteo de niveles, compra de materiales y soporte en obra',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  // Ingreso cobrado obra Calle Mayor:
  {
    id: 'tx-1',
    projectId: 'proj-1',
    projectName: 'Reforma Integral Calle Mayor 14',
    type: 'ingreso',
    category: 'pago_cliente',
    concept: 'Cobro primer hito - Adelanto de obra',
    netAmount: 3305.79,
    vatRate: 21.0,
    vatAmount: 694.21,
    grossAmount: 4000.00,
    paymentDate: '2026-09-01',
  },
  // Gasto compra materiales en Saltoki:
  {
    id: 'tx-2',
    projectId: 'proj-1',
    projectName: 'Reforma Integral Calle Mayor 14',
    type: 'gasto',
    category: 'materiales',
    concept: 'Factura F2026-892 Placas y Perfiles Saltoki',
    netAmount: 219.80,
    vatRate: 21.0,
    vatAmount: 46.16,
    grossAmount: 265.96,
    paymentDate: '2026-09-02',
  },
  // Gasto combustible furgoneta general de la empresa:
  {
    id: 'tx-3',
    type: 'gasto',
    category: 'combustible',
    concept: 'Gasoil furgoneta Repsol',
    netAmount: 74.38,
    vatRate: 21.0,
    vatAmount: 15.62,
    grossAmount: 90.00,
    paymentDate: '2026-09-04',
  },
];
